### ISSUE TITLE
multipath  topology not work in two seperate path

### ISSUE THREAD

**Issue by SoonyangZhang** [qdeconinck/minitopo#2]
I  build  a topology in mininet like following:  
```
                _________S1________________________            
   eth0  /10.0.1.1                     10.0.2.1           \      
h1                                                                  h2     
  eth1 \10.0.1.2                         10.0.2.2            /     
            \__________S2________________________  /       
``` 
but when I capture packet on h1-eth0 and h1-eth2, only  h1-eth0  has udp packets. it did not work.

And It works in the following topology. And the two paths that have udp packets are 10.0.0.2->10.0.2.2 and 10.0.1.2->10.0.2.2
![mp](https://user-images.githubusercontent.com/13272526/43696184-70f0653c-996f-11e8-8ee8-ec592da5b573.png)

**Comment by qdeconinck** [comment]
Could you bring more detail about what does not work (experiment run, logs)?

Did you tried to build the first topology inside minitopo? Where is h1-eth2?

**Comment by qdeconinck** [comment]
As it seems no further assistance is required, closing this issue.
